name: Run Tests

on:
  push:
    branches:
      - main  # Run on pushes to the main branch
  pull_request:
    branches:
      - main  # Run on pull requests targeting the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Checkout your repository

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Use Python 3.10 (match your project)

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .  # Install your project in editable mode
        pip install pytest  # Install pytest

    - name: Run tests with pytest
      run: pytest